export interface McqOption {
  id: string
  text: string
}

export interface McqItem {
  id: string
  question: string
  options: McqOption[]
  correctOptionId: string
  explanation: string
  topic: string
  category: 'react' | 'next-pages' | 'react-query' | 'axios' | 'styled-components' | 'testing' | 'decisions'
  difficulty: 'easy' | 'medium' | 'hard'
}

export const rickMortyProjectSummary = [
  'Proyecto: dashboard con tabs Characters/Locations usando la API de Rick & Morty.',
  'Stack solicitado: Next.js pages router (version vieja page-oriented), TypeScript, styled-components, Axios y React Query v5.',
  'Requisito clave: evitar refetch innecesario al cambiar tabs.',
  'Supuesto principal: primera pestaña toma /character y segunda /location.',
  'Sin paginacion/filtros/auth; UI simple para priorizar arquitectura y estado de datos.',
]

export const rickMortyInterviewQuestions = [
  'Como justificas usar pages router en vez de App Router para este challenge?',
  'Que cambiaria si migras este mismo proyecto a App Router?',
  'Como resolviste SSR de styled-components en _document y por que?',
  'Que parte pondrias en _app y cual dejarias por pagina?',
  'Por que decidiste usar React Query en lugar de useEffect + useState?',
  'Que query keys definiste y como evitaste colisiones?',
  'Como evitaste refetch al cambiar de tab?',
  'Que tradeoff tiene staleTime: Infinity en este contexto?',
  'Que haria falta para invalidar cache cuando backend cambia?',
  'Como manejas error/loading/empty state por tab?',
  'Por que elegiste Axios y no fetch nativo?',
  'Donde centralizaste baseURL y mapeo de respuestas?',
  'Que estrategia aplicaste para tipar Character y Location?',
  'Que haria si la API retorna campos nulos inesperados?',
  'Como evitarias rerenders innecesarios al cambiar tabs?',
  'Que ventaja tiene mantener ambas tabs montadas?',
  'Que desventaja tiene mantener ambas tabs montadas?',
  'Como implementarias lazy tab mounting sin romper UX?',
  'Como harias prefetch de la otra tab?',
  'Como agregarias paginacion sin duplicar logica?',
  'Que tests unitarios son clave para tabs + cache?',
  'Que tests de integracion haria para flujo completo?',
  'Como testearias que no hay refetch al volver a una tab?',
  'Que metricas usarias para evaluar performance real?',
  'Como manejarias rate limits o fallas intermitentes?',
  'Que cambios de accesibilidad faltan para produccion?',
  'Que cambios de observabilidad agregarias (logs/traces)?',
  'Que riesgos ves en hardcodear supuestos del brief?',
  'Como documentaste supuestos ambiguos del enunciado?',
  'Si tuvieras 1 hora extra, que mejora priorizarias y por que?',
  'Como implementarias paginado en Characters usando React Query v5 sin perder UX?',
  'Que queryKey usarias para paginado y por que?',
  'Usarias keepPreviousData en paginado? en que casos?',
  'Como evitarias saltos de layout mientras cambia de pagina?',
  'Que cambiaria en API client para soportar page param de forma tipada?',
  'Por que elegiste staleTime infinito y que tradeoffs tiene?',
  'Como resolverias SSR + styled-components en pages router?',
  'Que diferencia hay entre mantener tabs montados vs lazy mount?',
  'Como agregarias paginacion sin romper cache ni UX?',
  'Que estrategia usarias para retries y manejo de errores de API?',
  'Si la API cambia shape, donde encapsulas el mapper?',
  'Como testearias tabs y cache de React Query?',
  'Que metricas mirarias para evaluar performance real?',
  'Como evolucionarias el proyecto a App Router?',
  'Que mejoras haria falta para produccion (accesibilidad, observabilidad, seguridad)?',
]

export const rickMortyPaginationPlan = [
  'UI: agregar estado page por tab (Characters y Locations) con controles Prev/Next.',
  'Query keys: usar claves parametrizadas, por ejemplo [\'characters\', page] y [\'locations\', page].',
  'Fetchers: extender cliente Axios para aceptar { page } y mapear info/results de la API.',
  'UX: usar keepPreviousData para mantener cards anteriores mientras llega la nueva pagina.',
  'Estados: deshabilitar Prev en page=1 y Next cuando no exista info.next en la respuesta.',
  'Performance: opcionalmente prefetch de page+1 al resolver page actual.',
  'Testing: verificar que al cambiar page cambie queryKey y no se rompa cache de otras paginas.',
]

export const rickMortyMcq: McqItem[] = [
  {
    id: 'rm-01',
    topic: 'React Query',
    category: 'react-query',
    difficulty: 'easy',
    question: 'Que configuracion ayuda directamente a no refetchear al cambiar tabs si los datos ya se cargaron?',
    options: [
      { id: 'a', text: 'retry: false' },
      { id: 'b', text: 'staleTime: Infinity' },
      { id: 'c', text: 'refetchInterval: 1000' },
      { id: 'd', text: 'enabled: false permanente' },
    ],
    correctOptionId: 'b',
    explanation:
      'staleTime: Infinity mantiene la data fresca indefinidamente para React Query, por lo que al volver a la pestaña no dispara un refetch automatico.',
  },
  {
    id: 'rm-02',
    topic: 'Arquitectura',
    category: 'decisions',
    difficulty: 'easy',
    question: 'En el challenge, que ventaja concreta tiene mantener ambas tabs montadas y ocultar la inactiva?',
    options: [
      { id: 'a', text: 'Disminuye bundle size inicial' },
      { id: 'b', text: 'Elimina por completo las requests de red' },
      { id: 'c', text: 'Cambio instantaneo entre tabs y preserva estado local' },
      { id: 'd', text: 'Evita necesitar QueryClient' },
    ],
    correctOptionId: 'c',
    explanation:
      'Mantener montadas las vistas evita remount en cada switch y conserva estado local/UI, mejorando la fluidez del cambio de pestaña.',
  },
  {
    id: 'rm-03',
    topic: 'API',
    category: 'axios',
    difficulty: 'easy',
    question: 'Que endpoint corresponde a personajes segun la documentacion de Rick & Morty?',
    options: [
      { id: 'a', text: '/api/location' },
      { id: 'b', text: '/api/species' },
      { id: 'c', text: '/api/character' },
      { id: 'd', text: '/api/person' },
    ],
    correctOptionId: 'c',
    explanation: 'El endpoint oficial para personajes es /api/character.',
  },
  {
    id: 'rm-04',
    topic: 'TypeScript',
    category: 'decisions',
    difficulty: 'easy',
    question: 'Para evitar errores en tarjetas de personajes, que conviene tipar primero?',
    options: [
      { id: 'a', text: 'Solo el estado del tab activo' },
      { id: 'b', text: 'El objeto completo de respuesta de API y sus items' },
      { id: 'c', text: 'Solo los estilos de styled-components' },
      { id: 'd', text: 'Ningun tipo, usar any para iterar rapido' },
    ],
    correctOptionId: 'b',
    explanation:
      'Tipar respuesta + entidades reduce bugs de acceso a propiedades y facilita mapeos de UI con autocompletado confiable.',
  },
  {
    id: 'rm-05',
    topic: 'Styled-components',
    category: 'styled-components',
    difficulty: 'medium',
    question: 'En pages router, para SSR correcto con styled-components, donde suele hacerse la integracion?',
    options: [
      { id: 'a', text: 'En _document.tsx' },
      { id: 'b', text: 'En next.config.js solamente' },
      { id: 'c', text: 'Solo en componentes individuales' },
      { id: 'd', text: 'No requiere configuracion SSR' },
    ],
    correctOptionId: 'a',
    explanation:
      'En pages router, _document.tsx es el punto comun para colectar/inyectar estilos del server y evitar flicker/hydration mismatch.',
  },
  {
    id: 'rm-06',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'easy',
    question: 'Cual es una mejora simple para no repetir base URL en cada request?',
    options: [
      { id: 'a', text: 'Crear instancia de axios con baseURL' },
      { id: 'b', text: 'Usar fetch en paralelo con axios' },
      { id: 'c', text: 'Guardar URL en localStorage' },
      { id: 'd', text: 'Hardcodear en cada componente' },
    ],
    correctOptionId: 'a',
    explanation: 'Una instancia centralizada de axios mejora mantenibilidad y facilita agregar interceptors/timeouts.',
  },
  {
    id: 'rm-07',
    topic: 'React Query',
    category: 'react-query',
    difficulty: 'easy',
    question: 'Que queryKey es mejor para la tab Characters?',
    options: [
      { id: 'a', text: "['characters']" },
      { id: 'b', text: "['data']" },
      { id: 'c', text: "['tab']" },
      { id: 'd', text: "['items', Math.random()]" },
    ],
    correctOptionId: 'a',
    explanation: 'Una key semantica y estable como ["characters"] permite cache correcto e invalidez controlada.',
  },
  {
    id: 'rm-08',
    topic: 'UX',
    category: 'decisions',
    difficulty: 'medium',
    question: 'Si queres lazy load por tab y mantener buena UX, que estrategia es mejor?',
    options: [
      { id: 'a', text: 'Deshabilitar cache y recargar siempre' },
      { id: 'b', text: 'Prefetch de la tab no activa al hover/foco' },
      { id: 'c', text: 'No mostrar loading nunca' },
      { id: 'd', text: 'Fetch en useEffect sin query key' },
    ],
    correctOptionId: 'b',
    explanation: 'Prefetch reduce latencia percibida sin pagar costo completo de montar todo desde el inicio.',
  },
  {
    id: 'rm-09',
    topic: 'Errores',
    category: 'react-query',
    difficulty: 'easy',
    question: 'Que deberia mostrar cada tab cuando falla la API?',
    options: [
      { id: 'a', text: 'Pantalla en blanco' },
      { id: 'b', text: 'Solo console.log' },
      { id: 'c', text: 'Estado de error visible + opcion de retry' },
      { id: 'd', text: 'Recargar pagina automaticamente sin limite' },
    ],
    correctOptionId: 'c',
    explanation: 'Un estado de error visible y accionable mejora DX/UX y facilita depuracion.',
  },
  {
    id: 'rm-10',
    topic: 'Tradeoffs',
    category: 'decisions',
    difficulty: 'medium',
    question: 'Que desventaja puede tener staleTime: Infinity en produccion?',
    options: [
      { id: 'a', text: 'Los datos pueden quedar viejos si backend cambia' },
      { id: 'b', text: 'No funciona con TypeScript' },
      { id: 'c', text: 'Rompe axios' },
      { id: 'd', text: 'Impide renderizar listas' },
    ],
    correctOptionId: 'a',
    explanation: 'Sin invalidacion/policing, la data queda potencialmente stale por tiempo indeterminado.',
  },
  {
    id: 'rm-11',
    topic: 'Testing',
    category: 'testing',
    difficulty: 'easy',
    question: 'Que validarias primero en tests de este challenge?',
    options: [
      { id: 'a', text: 'Color exacto de cada card' },
      { id: 'b', text: 'Cambio de tab sin refetch innecesario' },
      { id: 'c', text: 'Orden alfabetico de commits' },
      { id: 'd', text: 'Tamaño de fuente del README' },
    ],
    correctOptionId: 'b',
    explanation: 'Es el requisito funcional mas critico del ejercicio, junto con render de data por tab.',
  },
  {
    id: 'rm-12',
    topic: 'Accessibility',
    category: 'react',
    difficulty: 'medium',
    question: 'Para tabs accesibles, que atributo es clave en el trigger activo?',
    options: [
      { id: 'a', text: 'aria-selected="true"' },
      { id: 'b', text: 'aria-hidden="true"' },
      { id: 'c', text: 'role="alert"' },
      { id: 'd', text: 'tabindex="-2"' },
    ],
    correctOptionId: 'a',
    explanation: 'aria-selected comunica a tecnologias asistivas cual tab esta activa.',
  },
  {
    id: 'rm-13',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'easy',
    question: 'En el modelo page-oriented, que archivo envuelve todas las paginas para providers globales?',
    options: [
      { id: 'a', text: '_app.tsx' },
      { id: 'b', text: '_document.tsx' },
      { id: 'c', text: 'layout.tsx' },
      { id: 'd', text: 'middleware.ts' },
    ],
    correctOptionId: 'a',
    explanation: '_app.tsx es el lugar tipico para envolver con QueryClientProvider y estilos globales en pages router.',
  },
  {
    id: 'rm-14',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'easy',
    question: 'Cual es la responsabilidad principal de _document.tsx en pages router?',
    options: [
      { id: 'a', text: 'Manejar estado de tabs' },
      { id: 'b', text: 'Customizar HTML shell del server' },
      { id: 'c', text: 'Definir query keys' },
      { id: 'd', text: 'Hacer fetch de API' },
    ],
    correctOptionId: 'b',
    explanation: '_document customiza html/head/body en SSR y es clave para styled-components SSR en pages.',
  },
  {
    id: 'rm-15',
    topic: 'React',
    category: 'react',
    difficulty: 'easy',
    question: 'Que bug comun aparece al usar index como key en listas?',
    options: [
      { id: 'a', text: 'No compila TypeScript' },
      { id: 'b', text: 'Desincroniza estado de filas al reordenar/eliminar' },
      { id: 'c', text: 'Rompe Axios' },
      { id: 'd', text: 'Impide SSR' },
    ],
    correctOptionId: 'b',
    explanation: 'Keys inestables hacen que React recicle nodos incorrectos, mezclando estado local entre elementos.',
  },
  {
    id: 'rm-16',
    topic: 'React Query',
    category: 'react-query',
    difficulty: 'medium',
    question: 'Que opcion conserva data previa durante cambios de key paginada?',
    options: [
      { id: 'a', text: 'keepPreviousData' },
      { id: 'b', text: 'suspense' },
      { id: 'c', text: 'gcTime: 0' },
      { id: 'd', text: 'retryDelay' },
    ],
    correctOptionId: 'a',
    explanation: 'keepPreviousData suaviza transiciones entre keys cercanas (ej. paginas) evitando flashes vacios.',
  },
  {
    id: 'rm-17',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'medium',
    question: 'Donde conviene normalizar errores HTTP para no repetir logica en cada tab?',
    options: [
      { id: 'a', text: 'Interceptor o helper de cliente API' },
      { id: 'b', text: 'Dentro de cada JSX card' },
      { id: 'c', text: 'En CSS' },
      { id: 'd', text: 'En package.json' },
    ],
    correctOptionId: 'a',
    explanation: 'Centralizar normalizacion de errores baja duplicacion y mejora consistencia de mensajes.',
  },
  {
    id: 'rm-18',
    topic: 'Decisiones',
    category: 'decisions',
    difficulty: 'medium',
    question: 'Que tradeoff tiene montar ambas tabs desde el inicio?',
    options: [
      { id: 'a', text: 'Mejor UX de switch pero mayor trabajo inicial' },
      { id: 'b', text: 'Menor uso de memoria y CPU inicial' },
      { id: 'c', text: 'Evita usar React Query' },
      { id: 'd', text: 'Hace imposible prefetch' },
    ],
    correctOptionId: 'a',
    explanation: 'Pre-cargar ambas vistas reduce latencia de cambio pero aumenta costo inicial de render/data.',
  },
  {
    id: 'rm-19',
    topic: 'Testing',
    category: 'testing',
    difficulty: 'medium',
    question: 'Para verificar no refetch en cambio de tabs, que assert es mas util?',
    options: [
      { id: 'a', text: 'Snapshot de toda la pagina' },
      { id: 'b', text: 'Cantidad de llamadas al cliente API' },
      { id: 'c', text: 'Comparar colores de botones' },
      { id: 'd', text: 'Medir tiempo con Date.now real' },
    ],
    correctOptionId: 'b',
    explanation: 'Contar llamadas a API valida de forma directa el comportamiento de cache/no refetch.',
  },
  {
    id: 'rm-20',
    topic: 'Styled-components',
    category: 'styled-components',
    difficulty: 'medium',
    question: 'Que problema evita la configuracion SSR correcta de styled-components?',
    options: [
      { id: 'a', text: 'Hydration mismatch y FOUC' },
      { id: 'b', text: 'Errores de CORS' },
      { id: 'c', text: 'Loop infinito en tabs' },
      { id: 'd', text: 'Doble fetch de Axios' },
    ],
    correctOptionId: 'a',
    explanation: 'Sin SSR style extraction puede aparecer flash de estilos y desajuste al hidratar.',
  },
  {
    id: 'rm-21',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'medium',
    question: 'Si quisieras SEO para contenido inicial en pages router, que tecnica es comun?',
    options: [
      { id: 'a', text: 'getServerSideProps o getStaticProps' },
      { id: 'b', text: 'Solo useEffect cliente' },
      { id: 'c', text: 'window.onload' },
      { id: 'd', text: 'setInterval' },
    ],
    correctOptionId: 'a',
    explanation: 'Pages router usa gSSP/gSP para data on-server y mejorar SEO/first paint.',
  },
  {
    id: 'rm-22',
    topic: 'React Query',
    category: 'react-query',
    difficulty: 'hard',
    question: 'Que riesgo hay si queryKey no incluye parametros variables relevantes?',
    options: [
      { id: 'a', text: 'Cache pollution y data incorrecta' },
      { id: 'b', text: 'Mejor performance siempre' },
      { id: 'c', text: 'Menos memoria usada seguro' },
      { id: 'd', text: 'No afecta nada' },
    ],
    correctOptionId: 'a',
    explanation: 'Si la key no distingue variantes, queries diferentes comparten cache y pueden mostrar data incorrecta.',
  },
  {
    id: 'rm-23',
    topic: 'React',
    category: 'react',
    difficulty: 'medium',
    question: 'Para togglear tabs, cuando conviene usar estado local simple en vez de store global?',
    options: [
      { id: 'a', text: 'Cuando el estado solo impacta la vista local' },
      { id: 'b', text: 'Nunca' },
      { id: 'c', text: 'Solo con Redux' },
      { id: 'd', text: 'Solo con server components' },
    ],
    correctOptionId: 'a',
    explanation: 'Estado local minimiza complejidad cuando no hay necesidad de compartirlo globalmente.',
  },
  {
    id: 'rm-24',
    topic: 'Decisiones',
    category: 'decisions',
    difficulty: 'hard',
    question: 'Que argumento de arquitectura explica mejor no sobre-ingenierizar este challenge?',
    options: [
      { id: 'a', text: 'El scope pide simplicidad y foco en requerimientos' },
      { id: 'b', text: 'Nunca usar patrones' },
      { id: 'c', text: 'Eliminar tipado para ir mas rapido' },
      { id: 'd', text: 'Evitar manejo de errores para reducir codigo' },
    ],
    correctOptionId: 'a',
    explanation: 'El objetivo del ejercicio es claridad y criterios de tradeoff, no complejidad artificial.',
  },
  {
    id: 'rm-25',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'easy',
    question: 'Que ventaja aporta un archivo lib/api.ts en este proyecto?',
    options: [
      { id: 'a', text: 'Centraliza cliente HTTP y facilita reuse/testing' },
      { id: 'b', text: 'Evita instalar axios' },
      { id: 'c', text: 'Reemplaza React Query' },
      { id: 'd', text: 'Hace SSR automatico' },
    ],
    correctOptionId: 'a',
    explanation: 'Un wrapper API desacopla UI de detalles HTTP y simplifica mocks en tests.',
  },
  {
    id: 'rm-26',
    topic: 'Testing',
    category: 'testing',
    difficulty: 'medium',
    question: 'Que combinacion de tests da mejor cobertura base aqui?',
    options: [
      { id: 'a', text: 'Solo snapshots' },
      { id: 'b', text: 'Unit para hooks + integration para tabs y estados' },
      { id: 'c', text: 'Solo e2e pesado' },
      { id: 'd', text: 'No testear cache' },
    ],
    correctOptionId: 'b',
    explanation: 'Unit + integration cubre logica de datos y UX sin costo excesivo de mantenimiento.',
  },
  {
    id: 'rm-27',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'easy',
    question: 'En pages router, donde suele configurarse ThemeProvider global de styled-components?',
    options: [
      { id: 'a', text: '_app.tsx' },
      { id: 'b', text: '_document.tsx' },
      { id: 'c', text: 'next.config.js' },
      { id: 'd', text: 'api route' },
    ],
    correctOptionId: 'a',
    explanation: '_app es el shell de pagina para providers de runtime como theme/query/router wrappers.',
  },
  {
    id: 'rm-28',
    topic: 'React Query',
    category: 'react-query',
    difficulty: 'medium',
    question: 'Que opcion controla tiempo de recoleccion de cache inactiva en v5?',
    options: [
      { id: 'a', text: 'gcTime' },
      { id: 'b', text: 'keepAliveMs' },
      { id: 'c', text: 'cacheTTL' },
      { id: 'd', text: 'timeoutCache' },
    ],
    correctOptionId: 'a',
    explanation: 'gcTime define cuanto vive en memoria una query inactiva antes de garbage collection.',
  },
  {
    id: 'rm-29',
    topic: 'React',
    category: 'react',
    difficulty: 'hard',
    question: 'Para prevenir race conditions en submit async de formularios, que patron es util?',
    options: [
      { id: 'a', text: 'Guard de isSubmitting + finally' },
      { id: 'b', text: 'setTimeout aleatorio' },
      { id: 'c', text: 'window.location.reload' },
      { id: 'd', text: 'Usar var global mutable' },
    ],
    correctOptionId: 'a',
    explanation: 'Bloquear re-entrada y cerrar ciclo en finally evita estados inconsistentes.',
  },
  {
    id: 'rm-30',
    topic: 'Decisiones',
    category: 'decisions',
    difficulty: 'medium',
    question: 'Que mejora de produccion priorizarias primero en este challenge?',
    options: [
      { id: 'a', text: 'Observabilidad y manejo robusto de errores' },
      { id: 'b', text: 'Animaciones complejas' },
      { id: 'c', text: 'Refactor total sin tests' },
      { id: 'd', text: 'Migracion inmediata a otro framework' },
    ],
    correctOptionId: 'a',
    explanation: 'Para un dashboard real, visibilidad operativa y resiliencia son criticos.',
  },
  {
    id: 'rm-31',
    topic: 'React Query',
    category: 'react-query',
    difficulty: 'easy',
    question: 'Que hook se usa para leer datos remotos en React Query?',
    options: [
      { id: 'a', text: 'useQuery' },
      { id: 'b', text: 'useReducer' },
      { id: 'c', text: 'useSignal' },
      { id: 'd', text: 'useStore' },
    ],
    correctOptionId: 'a',
    explanation: 'useQuery es el hook principal de lectura/caching de recursos remotos.',
  },
  {
    id: 'rm-32',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'easy',
    question: 'Cual de estos NO pertenece al modelo old pages router?',
    options: [
      { id: 'a', text: '_app.tsx' },
      { id: 'b', text: '_document.tsx' },
      { id: 'c', text: 'layout.tsx raiz del app router' },
      { id: 'd', text: 'pages/index.tsx' },
    ],
    correctOptionId: 'c',
    explanation: 'layout.tsx es paradigma App Router, no pieza central de pages router clasico.',
  },
  {
    id: 'rm-33',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'medium',
    question: 'Que campo de AxiosError es util para mapear status HTTP?',
    options: [
      { id: 'a', text: 'error.response?.status' },
      { id: 'b', text: 'error.stack[0]' },
      { id: 'c', text: 'error.config.headers.length' },
      { id: 'd', text: 'error.request.url.host' },
    ],
    correctOptionId: 'a',
    explanation: 'response.status es el dato directo para clasificar 4xx/5xx y mostrar mensaje adecuado.',
  },
  {
    id: 'rm-34',
    topic: 'Styled-components',
    category: 'styled-components',
    difficulty: 'easy',
    question: 'Que ventaja principal da styled-components en este ejercicio?',
    options: [
      { id: 'a', text: 'Scope de estilos por componente con API declarativa' },
      { id: 'b', text: 'Elimina necesidad de React' },
      { id: 'c', text: 'Remplaza React Query' },
      { id: 'd', text: 'Reduce requests HTTP' },
    ],
    correctOptionId: 'a',
    explanation: 'Facilita estilos encapsulados y mantenibles en componentes de cards/tabs.',
  },
  {
    id: 'rm-35',
    topic: 'Testing',
    category: 'testing',
    difficulty: 'hard',
    question: 'Para testear React Query en unit tests, que suele hacerse?',
    options: [
      { id: 'a', text: 'Crear QueryClient nuevo por test y limpiar cache' },
      { id: 'b', text: 'Reusar singleton global entre tests' },
      { id: 'c', text: 'Desactivar asserts async' },
      { id: 'd', text: 'No mockear API nunca' },
    ],
    correctOptionId: 'a',
    explanation: 'Aislar QueryClient por test evita coupling/flakiness por cache compartida.',
  },
  {
    id: 'rm-36',
    topic: 'React',
    category: 'react',
    difficulty: 'easy',
    question: 'Que estrategia evita stale closure en update de contador?',
    options: [
      { id: 'a', text: 'setState(prev => prev + 1)' },
      { id: 'b', text: 'setState(state + 1) siempre' },
      { id: 'c', text: 'Mutar variable externa' },
      { id: 'd', text: 'forzar rerender manual' },
    ],
    correctOptionId: 'a',
    explanation: 'Functional updates usan el valor mas reciente incluso bajo eventos rapidos.',
  },
  {
    id: 'rm-37',
    topic: 'Decisiones',
    category: 'decisions',
    difficulty: 'hard',
    question: 'Que suposicion ambigua del brief fue razonable documentar?',
    options: [
      { id: 'a', text: 'Texto duplicado de Locations cuando una era Characters' },
      { id: 'b', text: 'Eliminar TypeScript por comodidad' },
      { id: 'c', text: 'Agregar auth no solicitada' },
      { id: 'd', text: 'Cambiar API sin avisar' },
    ],
    correctOptionId: 'a',
    explanation: 'El brief repite bloque de Locations, por lo que explicitar interpretacion evita confusion evaluativa.',
  },
  {
    id: 'rm-38',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'medium',
    question: 'Si queres compartir metadata simple por pagina en pages router, que patron es comun?',
    options: [
      { id: 'a', text: 'next/head dentro de cada pagina' },
      { id: 'b', text: 'metadata export (app router only)' },
      { id: 'c', text: 'solo next.config.js' },
      { id: 'd', text: 'api routes' },
    ],
    correctOptionId: 'a',
    explanation: 'next/head es el enfoque clasico en pages router para title/meta tags por pantalla.',
  },
  {
    id: 'rm-39',
    topic: 'React Query',
    category: 'react-query',
    difficulty: 'medium',
    question: 'Que haria un buen fetcher si response viene no-200?',
    options: [
      { id: 'a', text: 'Throw error para que useQuery entre en estado error' },
      { id: 'b', text: 'Retornar null silenciosamente' },
      { id: 'c', text: 'Ignorar y seguir renderizando como exito' },
      { id: 'd', text: 'Recargar pagina' },
    ],
    correctOptionId: 'a',
    explanation: 'Lanzar error integra correctamente con isError/error UI de React Query.',
  },
  {
    id: 'rm-40',
    topic: 'Testing',
    category: 'testing',
    difficulty: 'easy',
    question: 'Que assert valida que una tab esta activa en UI accesible?',
    options: [
      { id: 'a', text: 'aria-selected=true en el tab activo' },
      { id: 'b', text: 'color exacto hexadecimal' },
      { id: 'c', text: 'cantidad de divs total' },
      { id: 'd', text: 'orden de imports' },
    ],
    correctOptionId: 'a',
    explanation: 'aria-selected permite assert funcional y accesible, menos fragil que estilos visuales.',
  },
  {
    id: 'rm-41',
    topic: 'Styled-components',
    category: 'styled-components',
    difficulty: 'hard',
    question: 'Que problema aparece si SSR de styled-components no recoge estilos en server?',
    options: [
      { id: 'a', text: 'FOUC y posible mismatch al hidratar' },
      { id: 'b', text: 'Axios deja de funcionar' },
      { id: 'c', text: 'React Query pierde cache' },
      { id: 'd', text: 'No compila TS' },
    ],
    correctOptionId: 'a',
    explanation: 'Sin collected styles en server, la app puede mostrar flash sin estilos al boot.',
  },
  {
    id: 'rm-42',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'hard',
    question: 'Que ventaja tiene mapear DTO externo a modelo interno antes de render?',
    options: [
      { id: 'a', text: 'Aislar cambios de API y estabilizar contrato de UI' },
      { id: 'b', text: 'Eliminar todos los tipos' },
      { id: 'c', text: 'Evitar usar hooks' },
      { id: 'd', text: 'Reducir bundle al 0%' },
    ],
    correctOptionId: 'a',
    explanation: 'Un mapper desacopla UI del proveedor externo y mejora mantenibilidad a largo plazo.',
  },
  {
    id: 'rm-43',
    topic: 'React',
    category: 'react',
    difficulty: 'medium',
    question: 'Que tecnica reduce renders en listas grandes de cards?',
    options: [
      { id: 'a', text: 'memoizacion de item y props estables' },
      { id: 'b', text: 'setState en cada render' },
      { id: 'c', text: 'index como key' },
      { id: 'd', text: 'inline object nuevo siempre' },
    ],
    correctOptionId: 'a',
    explanation: 'React.memo y props estables evitan renders repetidos en hijos sin cambios.',
  },
  {
    id: 'rm-44',
    topic: 'Decisiones',
    category: 'decisions',
    difficulty: 'easy',
    question: 'Por que este challenge no pide paginacion?',
    options: [
      { id: 'a', text: 'Porque busca evaluar decision making basico y cache, no feature-completeness' },
      { id: 'b', text: 'Porque API no soporta paginas' },
      { id: 'c', text: 'Porque Next no permite paginar' },
      { id: 'd', text: 'Porque React Query no sirve para eso' },
    ],
    correctOptionId: 'a',
    explanation: 'El brief recorta scope para observar claridad de implementacion y tradeoffs.',
  },
  {
    id: 'rm-45',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'hard',
    question: 'En pages router, cual es diferencia clave entre _app y _document?',
    options: [
      { id: 'a', text: '_app corre tambien en cliente; _document es server-only shell' },
      { id: 'b', text: '_document maneja estado React de tabs' },
      { id: 'c', text: '_app solo corre en server' },
      { id: 'd', text: 'Son intercambiables' },
    ],
    correctOptionId: 'a',
    explanation: '_app participa del runtime de pagina; _document solo customiza documento HTML del server.',
  },
  {
    id: 'rm-46',
    topic: 'React Query',
    category: 'react-query',
    difficulty: 'hard',
    question: 'Que estrategia combina rapidez inicial y bajo costo de red para tabs?',
    options: [
      { id: 'a', text: 'Lazy mount + prefetch de tab secundaria al primer idle' },
      { id: 'b', text: 'Refetch cada click' },
      { id: 'c', text: 'Desactivar cache totalmente' },
      { id: 'd', text: 'Requests secuenciales bloqueantes siempre' },
    ],
    correctOptionId: 'a',
    explanation: 'Combina costo inicial controlado con UX casi instantanea cuando usuario cambia de tab.',
  },
  {
    id: 'rm-47',
    topic: 'Testing',
    category: 'testing',
    difficulty: 'medium',
    question: 'Para tests de UI async, que API de RTL suele ser mas confiable?',
    options: [
      { id: 'a', text: 'findBy* y waitFor cuando aplica' },
      { id: 'b', text: 'setTimeout manual en cada test' },
      { id: 'c', text: 'solo getBy sin async' },
      { id: 'd', text: 'snapshot de loading' },
    ],
    correctOptionId: 'a',
    explanation: 'findBy/waitFor sincronizan con actualizaciones async reales y reducen flakes.',
  },
  {
    id: 'rm-48',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'easy',
    question: 'Que ventaja tiene setear timeout en axios para este challenge?',
    options: [
      { id: 'a', text: 'Evita requests colgadas indefinidamente y mejora control de error UX' },
      { id: 'b', text: 'Elimina necesidad de catch' },
      { id: 'c', text: 'Hace cache automatico' },
      { id: 'd', text: 'Aumenta SEO' },
    ],
    correctOptionId: 'a',
    explanation: 'Timeout razonable permite fallback claro cuando el backend demora demasiado.',
  },
  {
    id: 'rm-49',
    topic: 'React',
    category: 'react',
    difficulty: 'easy',
    question: 'Para una tab UI simple, cual state shape suele bastar?',
    options: [
      { id: 'a', text: 'activeTab: "characters" | "locations"' },
      { id: 'b', text: 'Store global con 20 reducers' },
      { id: 'c', text: 'Array de 200 flags' },
      { id: 'd', text: 'Objeto sin tipo any' },
    ],
    correctOptionId: 'a',
    explanation: 'Un estado minimo y claro facilita legibilidad y reduce sobre-ingenieria.',
  },
  {
    id: 'rm-50',
    topic: 'Decisiones',
    category: 'decisions',
    difficulty: 'hard',
    question: 'Cual respuesta refleja mejor criterio senior al explicar este challenge?',
    options: [
      { id: 'a', text: 'Cumpli requerimientos, documente supuestos, explicite tradeoffs y propuse mejoras concretas' },
      { id: 'b', text: 'Solo copie una solucion sin justificar' },
      { id: 'c', text: 'Priorice animaciones sobre requisitos' },
      { id: 'd', text: 'Ignore los puntos ambiguos del brief' },
    ],
    correctOptionId: 'a',
    explanation: 'Comunicar decisiones y limites es tan valioso como el codigo en evaluaciones reales.',
  },
  {
    id: 'rm-51',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'easy',
    question: 'En pages router, que funcion permite SSR en cada request?',
    options: [
      { id: 'a', text: 'getServerSideProps' },
      { id: 'b', text: 'getStaticProps' },
      { id: 'c', text: 'generateMetadata' },
      { id: 'd', text: 'server action' },
    ],
    correctOptionId: 'a',
    explanation: 'getServerSideProps ejecuta en servidor para cada request en el modelo pages.',
  },
  {
    id: 'rm-52',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'easy',
    question: 'Que funcion representa SSG en pages router?',
    options: [
      { id: 'a', text: 'getServerSideProps' },
      { id: 'b', text: 'getStaticProps' },
      { id: 'c', text: 'useSearchParams' },
      { id: 'd', text: 'revalidatePath' },
    ],
    correctOptionId: 'b',
    explanation: 'getStaticProps genera HTML en build time y puede combinarse con ISR.',
  },
  {
    id: 'rm-53',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'medium',
    question: 'Como se habilita ISR en pages router?',
    options: [
      { id: 'a', text: 'Devolviendo revalidate en getStaticProps' },
      { id: 'b', text: 'Agregando cache: force-cache al fetch' },
      { id: 'c', text: 'Usando middleware obligatorio' },
      { id: 'd', text: 'Con useEffect y setInterval' },
    ],
    correctOptionId: 'a',
    explanation: 'El campo revalidate en getStaticProps activa regeneration incremental.',
  },
  {
    id: 'rm-54',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'medium',
    question: 'Que hook de pages router se usa para navegar programaticamente?',
    options: [
      { id: 'a', text: 'useNavigate' },
      { id: 'b', text: 'useRouter de next/router' },
      { id: 'c', text: 'useHistory de react-router' },
      { id: 'd', text: 'usePathname de next/navigation' },
    ],
    correctOptionId: 'b',
    explanation: 'En pages router clasico se usa next/router.',
  },
  {
    id: 'rm-55',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'hard',
    question: 'Que hace router.push(url, as, { shallow: true }) en pages router?',
    options: [
      { id: 'a', text: 'Cambia URL sin re-ejecutar data methods de pagina actual' },
      { id: 'b', text: 'Fuerza full reload del documento' },
      { id: 'c', text: 'Limpia cache de React Query' },
      { id: 'd', text: 'Solo funciona en App Router' },
    ],
    correctOptionId: 'a',
    explanation: 'Shallow routing evita reruns de gSSP/gSP en la misma pagina para cambios de query.',
  },
  {
    id: 'rm-56',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'hard',
    question: 'En pages router, por que getInitialProps se considera legacy?',
    options: [
      { id: 'a', text: 'Reduce optimizaciones automaticas y mezcla server/client data fetching' },
      { id: 'b', text: 'No permite TypeScript' },
      { id: 'c', text: 'No funciona con _app' },
      { id: 'd', text: 'Rompe CSS modules' },
    ],
    correctOptionId: 'a',
    explanation: 'getInitialProps limita optimizaciones modernas y se prefiere gSSP/gSP.',
  },
  {
    id: 'rm-57',
    topic: 'React',
    category: 'react',
    difficulty: 'easy',
    question: 'Cuando useMemo es realmente util?',
    options: [
      { id: 'a', text: 'Para memorizar computos caros o valores estables para hijos memoizados' },
      { id: 'b', text: 'Siempre, incluso para strings literales' },
      { id: 'c', text: 'Solo en class components' },
      { id: 'd', text: 'Para reemplazar useState' },
    ],
    correctOptionId: 'a',
    explanation: 'useMemo tiene costo, se aplica donde evita trabajo o rerenders relevantes.',
  },
  {
    id: 'rm-58',
    topic: 'React',
    category: 'react',
    difficulty: 'medium',
    question: 'Que problema evita useCallback en handlers pasados a hijos memoizados?',
    options: [
      { id: 'a', text: 'Recreacion de referencia que dispara rerender innecesario' },
      { id: 'b', text: 'Errores HTTP 500' },
      { id: 'c', text: 'Perdida de SSR' },
      { id: 'd', text: 'Incompatibilidad con TypeScript' },
    ],
    correctOptionId: 'a',
    explanation: 'useCallback estabiliza referencias de funciones y ayuda a React.memo.',
  },
  {
    id: 'rm-59',
    topic: 'React',
    category: 'react',
    difficulty: 'medium',
    question: 'Que tecnica es recomendable para evitar update state after unmount?',
    options: [
      { id: 'a', text: 'Cleanup con bandera/cancelacion en useEffect' },
      { id: 'b', text: 'setTimeout mas largo' },
      { id: 'c', text: 'try/catch vacio' },
      { id: 'd', text: 'window.stop()' },
    ],
    correctOptionId: 'a',
    explanation: 'El cleanup de effect previene writes cuando el componente ya no esta montado.',
  },
  {
    id: 'rm-60',
    topic: 'React',
    category: 'react',
    difficulty: 'hard',
    question: 'Que describe mejor la reconciliacion de React con keys estables?',
    options: [
      { id: 'a', text: 'Permite mapear nodos previos/siguientes con menor trabajo y menos bugs de estado' },
      { id: 'b', text: 'Fuerza remount de todos los hijos' },
      { id: 'c', text: 'Solo impacta estilos, no estado' },
      { id: 'd', text: 'Es irrelevante para listas' },
    ],
    correctOptionId: 'a',
    explanation: 'Keys estables mejoran diffing y preservan estado correcto por item.',
  },
  {
    id: 'rm-61',
    topic: 'React',
    category: 'react',
    difficulty: 'hard',
    question: 'Que tradeoff hay entre controlled vs uncontrolled inputs?',
    options: [
      { id: 'a', text: 'Controlled da control total y validacion simple, pero mas rerenders' },
      { id: 'b', text: 'Uncontrolled siempre es mas seguro' },
      { id: 'c', text: 'Controlled no funciona con hooks' },
      { id: 'd', text: 'No existe diferencia practica' },
    ],
    correctOptionId: 'a',
    explanation: 'Controlled centraliza estado y validacion, a costo de mayor trabajo de render/estado.',
  },
  {
    id: 'rm-62',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'medium',
    question: 'Para rutas dinamicas en pages router, cual archivo es correcto?',
    options: [
      { id: 'a', text: 'pages/character/[id].tsx' },
      { id: 'b', text: 'pages/character/:id.tsx' },
      { id: 'c', text: 'app/character/[id]/page.tsx solamente' },
      { id: 'd', text: 'pages/character/id.tsx' },
    ],
    correctOptionId: 'a',
    explanation: 'El patron dinamico de pages usa corchetes en el nombre de archivo.',
  },
  {
    id: 'rm-63',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'hard',
    question: 'Que haria para evitar doble fetch inicial de tabs manteniendo pages router?',
    options: [
      { id: 'a', text: 'Lazy fetch por tab activa + prefetch posterior opcional' },
      { id: 'b', text: 'Desactivar cache y refetch on focus' },
      { id: 'c', text: 'Renderizar ambas tabs con fetch bloqueante siempre' },
      { id: 'd', text: 'Mover todo a middleware' },
    ],
    correctOptionId: 'a',
    explanation: 'Ese enfoque reduce costo inicial y mantiene UX buena con prefetch inteligente.',
  },
  {
    id: 'rm-64',
    topic: 'React',
    category: 'react',
    difficulty: 'easy',
    question: 'Que hook usar para guardar referencia mutable sin rerender?',
    options: [
      { id: 'a', text: 'useRef' },
      { id: 'b', text: 'useMemo' },
      { id: 'c', text: 'useContext' },
      { id: 'd', text: 'useId' },
    ],
    correctOptionId: 'a',
    explanation: 'useRef mantiene valor mutable estable entre renders sin dispararlos.',
  },
  {
    id: 'rm-65',
    topic: 'React',
    category: 'react',
    difficulty: 'medium',
    question: 'Cuando conviene usar useReducer en vez de varios useState?',
    options: [
      { id: 'a', text: 'Cuando hay transiciones de estado relacionadas y logica de acciones clara' },
      { id: 'b', text: 'Siempre para cualquier booleano' },
      { id: 'c', text: 'Nunca en functional components' },
      { id: 'd', text: 'Solo para formularios de un input' },
    ],
    correctOptionId: 'a',
    explanation: 'useReducer mejora claridad en estados complejos con acciones explicitas.',
  },
  {
    id: 'rm-66',
    topic: 'Next Pages',
    category: 'next-pages',
    difficulty: 'medium',
    question: 'Que tecnica de pages router ayuda a reducir JS inicial en rutas no visitadas?',
    options: [
      { id: 'a', text: 'Code splitting automatico por pagina' },
      { id: 'b', text: 'Disable webpack' },
      { id: 'c', text: 'Un unico archivo gigante de rutas' },
      { id: 'd', text: 'Inline todo en _app' },
    ],
    correctOptionId: 'a',
    explanation: 'Cada pagina se divide en chunk y se carga bajo demanda cuando se navega.',
  },
  {
    id: 'rm-67',
    topic: 'Testing',
    category: 'testing',
    difficulty: 'medium',
    question: 'Que assert validaria decision de no refetch al volver a Characters?',
    options: [
      { id: 'a', text: 'expect(api.getCharacters).toHaveBeenCalledTimes(1)' },
      { id: 'b', text: 'expect(document.body).toMatchSnapshot()' },
      { id: 'c', text: 'expect(window.location.href).toContain("char")' },
      { id: 'd', text: 'expect(true).toBe(true)' },
    ],
    correctOptionId: 'a',
    explanation: 'El conteo de llamadas valida estrictamente el requerimiento de no refetch innecesario.',
  },
  {
    id: 'rm-68',
    topic: 'Decisiones',
    category: 'decisions',
    difficulty: 'hard',
    question: 'En una entrevista, que respuesta muestra mejor ownership tecnico?',
    options: [
      { id: 'a', text: 'Explicar supuestos, riesgos, tradeoffs y plan de evolucion del proyecto' },
      { id: 'b', text: 'Decir que solo importo cumplir rapido' },
      { id: 'c', text: 'Evitar hablar de limites de la solucion' },
      { id: 'd', text: 'Culpar al enunciado por todo' },
    ],
    correctOptionId: 'a',
    explanation: 'Ownership incluye justificar decisiones y mostrar criterio de evolucion.',
  },
  {
    id: 'rm-69',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'easy',
    question: 'Que hook se usa para ejecutar efectos secundarios luego del render?',
    options: [
      { id: 'a', text: 'useEffect' },
      { id: 'b', text: 'useMemo' },
      { id: 'c', text: 'useId' },
      { id: 'd', text: 'useRef' },
    ],
    correctOptionId: 'a',
    explanation: 'useEffect sirve para sincronizar con sistemas externos: fetch, listeners, timers, etc.',
  },
  {
    id: 'rm-70',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'medium',
    question: 'Que pasa si olvidas dependencias en useEffect?',
    options: [
      { id: 'a', text: 'Siempre mejora performance' },
      { id: 'b', text: 'Puede causar stale values o comportamientos inconsistentes' },
      { id: 'c', text: 'React agrega deps automaticamente en runtime' },
      { id: 'd', text: 'Solo afecta a TypeScript' },
    ],
    correctOptionId: 'b',
    explanation: 'Dependencias incompletas rompen sincronizacion y pueden usar datos viejos (stale closures).',
  },
  {
    id: 'rm-71',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'medium',
    question: 'Cual es el orden correcto de cleanup en useEffect?',
    options: [
      { id: 'a', text: 'Cleanup se ejecuta antes del siguiente effect y al unmount' },
      { id: 'b', text: 'Cleanup solo se ejecuta en errores' },
      { id: 'c', text: 'Cleanup se ejecuta una sola vez al mount' },
      { id: 'd', text: 'Cleanup no existe en hooks' },
    ],
    correctOptionId: 'a',
    explanation: 'React limpia el efecto previo antes de correr el nuevo, y tambien al desmontar.',
  },
  {
    id: 'rm-72',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'hard',
    question: 'Que anti-pattern evita useMemo?',
    options: [
      { id: 'a', text: 'Recalcular en cada render un computo costoso sin necesidad' },
      { id: 'b', text: 'Uso de JSX' },
      { id: 'c', text: 'Estado local en formularios' },
      { id: 'd', text: 'Uso de TypeScript generics' },
    ],
    correctOptionId: 'a',
    explanation: 'useMemo evita trabajo repetido cuando las dependencias no cambian.',
  },
  {
    id: 'rm-73',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'hard',
    question: 'Cuando useCallback no aporta casi nada?',
    options: [
      { id: 'a', text: 'Cuando la funcion no se pasa a hijos memoizados ni depende de recomputos caros' },
      { id: 'b', text: 'Cuando hay TypeScript' },
      { id: 'c', text: 'Cuando hay mas de un button' },
      { id: 'd', text: 'Siempre aporta lo mismo' },
    ],
    correctOptionId: 'a',
    explanation: 'useCallback tambien tiene costo; se justifica cuando mejora render o estabilidad de dependencias.',
  },
  {
    id: 'rm-74',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'easy',
    question: 'Que hook te permite exponer una API reutilizable de estado/logica?',
    options: [
      { id: 'a', text: 'Custom hook' },
      { id: 'b', text: 'Fragment' },
      { id: 'c', text: 'Portal' },
      { id: 'd', text: 'Profiler' },
    ],
    correctOptionId: 'a',
    explanation: 'Los custom hooks encapsulan logica reutilizable sin duplicarla en componentes.',
  },
  {
    id: 'rm-75',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'medium',
    question: 'Regla clave de hooks: donde deben llamarse?',
    options: [
      { id: 'a', text: 'Solo en top-level de componentes o custom hooks' },
      { id: 'b', text: 'Dentro de if/for para optimizar' },
      { id: 'c', text: 'Solo en clases' },
      { id: 'd', text: 'En cualquier callback async' },
    ],
    correctOptionId: 'a',
    explanation: 'Mantener orden de llamadas estable es esencial para que React asigne estado correcto.',
  },
  {
    id: 'rm-76',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'medium',
    question: 'Que hook usar para guardar valor previo entre renders sin rerender inmediato?',
    options: [
      { id: 'a', text: 'useRef' },
      { id: 'b', text: 'useMemo' },
      { id: 'c', text: 'useLayoutEffect' },
      { id: 'd', text: 'useId' },
    ],
    correctOptionId: 'a',
    explanation: 'useRef mantiene current mutable entre renders sin disparar nuevo render.',
  },
  {
    id: 'rm-77',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'hard',
    question: 'En StrictMode dev, por que parece que useEffect se ejecuta dos veces?',
    options: [
      { id: 'a', text: 'React re-monta para detectar efectos no idempotentes en desarrollo' },
      { id: 'b', text: 'Es bug de producción' },
      { id: 'c', text: 'Axios fuerza doble mount' },
      { id: 'd', text: 'Siempre pasa tambien en production' },
    ],
    correctOptionId: 'a',
    explanation: 'Es comportamiento intencional en dev para detectar side effects inseguros.',
  },
  {
    id: 'rm-78',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'hard',
    question: 'Que problema resuelve usar updater function en setState?',
    options: [
      { id: 'a', text: 'Evita stale state cuando hay updates batched o concurrentes' },
      { id: 'b', text: 'Evita escribir dependencias en effects' },
      { id: 'c', text: 'Reemplaza completamente useReducer' },
      { id: 'd', text: 'Hace que todo sea sync' },
    ],
    correctOptionId: 'a',
    explanation: 'setState(prev => ...) calcula desde el valor real mas reciente.',
  },
  {
    id: 'rm-79',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'medium',
    question: 'En custom hooks async, que mejora evita race conditions de respuestas viejas?',
    options: [
      { id: 'a', text: 'Request id / cancel flag en cleanup' },
      { id: 'b', text: 'sleep aleatorio antes de setState' },
      { id: 'c', text: 'Eliminar manejo de errores' },
      { id: 'd', text: 'Usar any en tipos' },
    ],
    correctOptionId: 'a',
    explanation: 'Comparar request activa o cancelar en cleanup evita pisar estado con respuestas atrasadas.',
  },
  {
    id: 'rm-80',
    topic: 'React Hooks',
    category: 'react',
    difficulty: 'easy',
    question: 'Cual es la forma correcta de derivar UI de estado en React?',
    options: [
      { id: 'a', text: 'Render declarativo desde estado/props, evitando mutar DOM manualmente' },
      { id: 'b', text: 'querySelector y classList directo en cada click' },
      { id: 'c', text: 'setInterval forzando rerenders' },
      { id: 'd', text: 'Guardar JSX en localStorage' },
    ],
    correctOptionId: 'a',
    explanation: 'El modelo declarativo es base de hooks y evita inconsistencias de UI.',
  },
  {
    id: 'rm-81',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'medium',
    question: 'Para paginado en React Query v5, que queryKey representa mejor la pagina actual?',
    options: [
      { id: 'a', text: "['characters']" },
      { id: 'b', text: "['characters', page]" },
      { id: 'c', text: "['page']" },
      { id: 'd', text: "['characters', Math.random()]" },
    ],
    correctOptionId: 'b',
    explanation: 'Incluir page en la key separa cache por pagina y evita colisiones entre resultados.',
  },
  {
    id: 'rm-82',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'medium',
    question: 'Que feature ayuda a evitar flash vacio al cambiar de pagina?',
    options: [
      { id: 'a', text: 'keepPreviousData' },
      { id: 'b', text: 'retry: 10' },
      { id: 'c', text: 'gcTime: 0' },
      { id: 'd', text: 'suspense: false' },
    ],
    correctOptionId: 'a',
    explanation: 'keepPreviousData mantiene la data anterior mientras llega la nueva pagina.',
  },
  {
    id: 'rm-83',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'hard',
    question: 'Que hook seria ideal para paginado infinito en vez de botones Prev/Next?',
    options: [
      { id: 'a', text: 'useInfiniteQuery' },
      { id: 'b', text: 'useMutation' },
      { id: 'c', text: 'useSuspenseQuery' },
      { id: 'd', text: 'useDeferredValue' },
    ],
    correctOptionId: 'a',
    explanation: 'useInfiniteQuery modela cursores/paginas encadenadas con fetchNextPage.',
  },
  {
    id: 'rm-84',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'hard',
    question: 'En v5, que opcion controla cuanto vive cache inactiva?',
    options: [
      { id: 'a', text: 'gcTime' },
      { id: 'b', text: 'cacheTime' },
      { id: 'c', text: 'timeToLive' },
      { id: 'd', text: 'staleSeconds' },
    ],
    correctOptionId: 'a',
    explanation: 'En TanStack Query v5 se usa gcTime para garbage collection de queries inactivas.',
  },
  {
    id: 'rm-85',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'medium',
    question: 'Que haria para precargar la siguiente pagina tras cargar la actual?',
    options: [
      { id: 'a', text: 'queryClient.prefetchQuery con key de page+1' },
      { id: 'b', text: 'setTimeout y reload de pagina' },
      { id: 'c', text: 'Desactivar cache' },
      { id: 'd', text: 'Usar localStorage manual para todo' },
    ],
    correctOptionId: 'a',
    explanation: 'PrefetchQuery mejora percepcion de velocidad al navegar a la siguiente pagina.',
  },
  {
    id: 'rm-86',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'easy',
    question: 'Como construirias request paginada de characters con Axios?',
    options: [
      { id: 'a', text: 'axios.get(\'/character\', { params: { page } })' },
      { id: 'b', text: 'axios.post(\'/character\', page)' },
      { id: 'c', text: 'axios.get(page)' },
      { id: 'd', text: 'axios.delete(\'/character?page=\'+page)' },
    ],
    correctOptionId: 'a',
    explanation: 'params serializa query string de forma limpia y tipable.',
  },
  {
    id: 'rm-87',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'medium',
    question: 'Que estructura conviene tipar para paginado de Rick & Morty API?',
    options: [
      { id: 'a', text: '{ info: { next, prev, pages }, results: T[] }' },
      { id: 'b', text: '{ data: string }' },
      { id: 'c', text: '{ totalOnly: number }' },
      { id: 'd', text: '{ ok: boolean }' },
    ],
    correctOptionId: 'a',
    explanation: 'La API retorna metadata en info y elementos en results.',
  },
  {
    id: 'rm-88',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'hard',
    question: 'Que mejora de robustez aplicarias en cliente Axios para errores paginados?',
    options: [
      { id: 'a', text: 'Normalizar AxiosError y mapear 404 de pagina inexistente a estado controlado' },
      { id: 'b', text: 'Ignorar todos los errores de red' },
      { id: 'c', text: 'Relanzar errores sin contexto' },
      { id: 'd', text: 'Hacer window.location.reload en cada error' },
    ],
    correctOptionId: 'a',
    explanation: 'Mapping de errores mejora UX y evita crashear la vista por pagina invalida.',
  },
  {
    id: 'rm-89',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'medium',
    question: 'Que estado de query es util para mostrar spinner sutil al cambiar page manteniendo datos previos?',
    options: [
      { id: 'a', text: 'isFetching' },
      { id: 'b', text: 'isPaused' },
      { id: 'c', text: 'isIdle' },
      { id: 'd', text: 'status === success solamente' },
    ],
    correctOptionId: 'a',
    explanation: 'isFetching puede estar true mientras hay datos, ideal para loading no intrusivo.',
  },
  {
    id: 'rm-90',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'hard',
    question: 'Que estrategia evita mezclar cache de Characters y Locations paginados?',
    options: [
      { id: 'a', text: 'Separar query keys por recurso y pagina: [\'characters\', page], [\'locations\', page]' },
      { id: 'b', text: 'Usar una sola key [\'list\'] para todo' },
      { id: 'c', text: 'Desactivar cache globalmente' },
      { id: 'd', text: 'Guardar todo en un useState unico' },
    ],
    correctOptionId: 'a',
    explanation: 'Keys bien modeladas evitan colisiones entre datasets distintos.',
  },
  {
    id: 'rm-91',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'medium',
    question: 'Donde ubicar el helper fetchCharactersPage para mantener arquitectura limpia?',
    options: [
      { id: 'a', text: 'En capa lib/api o services separada de componentes' },
      { id: 'b', text: 'Inline dentro del JSX de cada card' },
      { id: 'c', text: 'Dentro de CSS' },
      { id: 'd', text: 'En package.json scripts' },
    ],
    correctOptionId: 'a',
    explanation: 'Separar cliente de datos de UI facilita testeo y mantenimiento.',
  },
  {
    id: 'rm-92',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'easy',
    question: 'Que hace useQuery cuando la queryKey cambia de [\'characters\',1] a [\'characters\',2]?',
    options: [
      { id: 'a', text: 'Trata la query como distinta y consulta/lee cache de esa nueva key' },
      { id: 'b', text: 'Ignora el cambio de key' },
      { id: 'c', text: 'Rompe el QueryClient' },
      { id: 'd', text: 'Borra todo el cache' },
    ],
    correctOptionId: 'a',
    explanation: 'La key define identidad de query; cambiarla selecciona otro registro de cache.',
  },
  {
    id: 'rm-93',
    topic: 'Axios',
    category: 'axios',
    difficulty: 'hard',
    question: 'Que ventaja tiene usar interceptors para este challenge?',
    options: [
      { id: 'a', text: 'Centralizar logging, headers y normalizacion de errores en un punto' },
      { id: 'b', text: 'Eliminar necesidad de await' },
      { id: 'c', text: 'Reemplazar React Query' },
      { id: 'd', text: 'Evitar TypeScript' },
    ],
    correctOptionId: 'a',
    explanation: 'Interceptors evitan repetir logica transversal en cada fetcher.',
  },
  {
    id: 'rm-94',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'medium',
    question: 'Si queres que al volver a una pagina ya visitada no se refetchee enseguida, que ajustar?',
    options: [
      { id: 'a', text: 'staleTime adecuado (>0) segun tolerancia de frescura' },
      { id: 'b', text: 'retry infinito' },
      { id: 'c', text: 'gcTime=0' },
      { id: 'd', text: 'enabled=false siempre' },
    ],
    correctOptionId: 'a',
    explanation: 'staleTime determina cuanto tiempo se considera fresca la data para evitar refetch inmediato.',
  },
  {
    id: 'rm-95',
    topic: 'React Query v5',
    category: 'react-query',
    difficulty: 'hard',
    question: 'Que diseño permite paginado por tab sin ensuciar state global?',
    options: [
      { id: 'a', text: 'Estado local de page por tab + query keys parametrizadas + fetchers puros' },
      { id: 'b', text: 'Una variable global mutable window.page' },
      { id: 'c', text: 'No usar query keys' },
      { id: 'd', text: 'Un solo endpoint para todo sin params' },
    ],
    correctOptionId: 'a',
    explanation: 'Combina encapsulacion, cache correcto y bajo acoplamiento entre vistas.',
  },
]

